cursor #ede7f0
cursor_text_color #f5eff8

foreground            #ede7f0
background            #000000
selection_foreground  #000000
selection_background  #8b7895
url_color             #8050a8

color0   #000000
color1   #c15165
color2   #50a864
color3   #d2b358
color4   #713b9f
color5   #2b034d
color6   #8050A8
color7   #aba5b0
color8   #69646d
color9   #e28999
color10  #7fc991
color11  #fce49f
color12  #9366b8
color13  #b58ada
color14  #d1b3eb
color15  #f0edf3
