-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(8050a8)",
			inactive_border = "rgb(493653)",
		},
	},
	group = {
		col = {
			border_active = "rgb(8050a8)",
			border_inactive = "rgb(493653)",
			border_locked_active = "rgb(d94a52)",
			border_locked_inactive = "rgb(493653)",
		},
		groupbar = {
			col = {
				active = "rgb(8050a8)",
				inactive = "rgb(493653)",
				locked_active = "rgb(d94a52)",
				locked_inactive = "rgb(493653)",
			},
		},
	},
})
