splash = false

wallpaper {
	monitor = DP-3
	path = /home/carmelo/Pictures/wallpapers/a_painting_of_a_man_with_a_face_on_his_head_upscayl_4x_upscayl-standard-4x.png
	fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/carmelo/Pictures/wallpapers/a_painting_of_a_man_with_a_face_on_his_head_upscayl_4x_upscayl-standard-4x.png
  fit_mode = cover
}
