preload = /home/carmelo/Pictures/wallpapers/a_painting_of_a_man_with_a_face_on_his_head_upscayl_4x_upscayl-standard-4x.png
wallpaper = ,/home/carmelo/Pictures/wallpapers/a_painting_of_a_man_with_a_face_on_his_head_upscayl_4x_upscayl-standard-4x.png
