#!/bin/bash

SOURCE="@DEFAULT_AUDIO_SOURCE@"

wpctl set-mute "$SOURCE" toggle

if wpctl get-volume "$SOURCE" | grep -q MUTED; then
    paplay ~/.config/sounds/mute.wav
    notify-send "Microphone" "🔇 Muted"
else
    paplay ~/.config/sounds/unmute.wav
    notify-send "Microphone" "🎙️ Unmuted"
fi
